language: php

php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

matrix:
  allow_failures:
  - php: hhvm
  - php: nightly

before_install:
  - composer self-update

install:
  - composer update --ignore-platform-reqs

script:
  composer test
