language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
  - php: hhvm

before_install:
  - composer self-update
  - if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then echo "hhvm.php7.all=1" >> /tmp/hhvm.php.ini; fi

install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm* ]]; then composer update; else composer update --ignore-platform-reqs; fi

script:
  composer test
