version: 2

default_steps: &default_steps
  steps:
    - checkout

    # System
    - run:
        name: Install system dependencies
        command: |
          sudo apt update -yq
          sudo apt install libpng-dev libfreetype6-dev libjpeg62-turbo-dev -yq
          sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
          sudo docker-php-ext-install -j$(nproc) gd

    # Composer
    - run:
        name: Set Illuminate version
        command: |
          composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
          composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update
          composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --dev
          composer require "orchestra/database:${TESTBENCH_VERSION}" --no-update --dev
    - restore_cache:
        name: Restore Composer package cache
        keys:
          - composer-packages-{{ .Branch }}-{{ checksum "composer.json" }}
          - composer-packages-{{ .Branch }}
          - composer-packages-master
          - composer-packages-
    - run:
        name: Run Composer
        command: |
          if [[ $SETUP = 'stable' ]]; then  composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
          if [[ $SETUP = 'lowest' ]]; then  composer update --prefer-dist --no-interaction --prefer-stable --no-suggest --prefer-lowest; fi
    - save_cache:
        name: Save Composer package cache
        key: composer-packages-{{ .Branch }}-{{ checksum "composer.json" }}
        paths:
          - vendor

    # Tests
    - run:
        name: Run tests
        command: |
          mkdir -p tests/phpunit
          vendor/bin/phpunit --coverage-clover tests/coverage_clover.xml --log-junit tests/phpunit/junit.xml
          php vendor/bin/codacycoverage clover tests/coverage_clover.xml
    - store_test_results:
        path: tests/phpunit

jobs:
  php-7.0-l-5.4:
    docker:
      - image: circleci/php:7.0
    environment:
      SETUP: stable
      ILLUMINATE_VERSION: 5.4
      TESTBENCH_VERSION: 3.4

    <<: *default_steps

  php-7.0-lowest-l-5.4:
    docker:
      - image: circleci/php:7.0
    environment:
      SETUP: lowest
      ILLUMINATE_VERSION: 5.4
      TESTBENCH_VERSION: 3.4

    <<: *default_steps

  php-7.0-l-5.5:
    docker:
      - image: circleci/php:7.0
    environment:
      SETUP: stable
      ILLUMINATE_VERSION: 5.5
      TESTBENCH_VERSION: 3.5

    <<: *default_steps

  php-7.0-lowest-l-5.5:
    docker:
      - image: circleci/php:7.0
    environment:
      SETUP: lowest
      ILLUMINATE_VERSION: 5.5
      TESTBENCH_VERSION: 3.5

    <<: *default_steps

  php-7.1-l-5.6:
    docker:
      - image: circleci/php:7.1
    environment:
      SETUP: stable
      ILLUMINATE_VERSION: 5.6
      TESTBENCH_VERSION: 3.6

    <<: *default_steps

  php-7.1-lowest-l-5.6:
    docker:
      - image: circleci/php:7.1
    environment:
      SETUP: lowest
      ILLUMINATE_VERSION: 5.6
      TESTBENCH_VERSION: 3.6

    <<: *default_steps

  php-7.2-l-5.4:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: stable
      ILLUMINATE_VERSION: 5.4
      TESTBENCH_VERSION: 3.4

    <<: *default_steps

  php-7.2-lowest-l-5.4:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: lowest
      ILLUMINATE_VERSION: 5.4
      TESTBENCH_VERSION: 3.4

    <<: *default_steps

  php-7.2-l-5.5:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: stable
      ILLUMINATE_VERSION: 5.5
      TESTBENCH_VERSION: 3.5

    <<: *default_steps

  php-7.2-lowest-l-5.5:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: lowest
      ILLUMINATE_VERSION: 5.5
      TESTBENCH_VERSION: 3.5

    <<: *default_steps

  php-7.2-l-5.6:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: stable
      ILLUMINATE_VERSION: 5.6
      TESTBENCH_VERSION: 3.6

    <<: *default_steps

  php-7.2-lowest-l-5.6:
    docker:
      - image: circleci/php:7.2
    environment:
      SETUP: lowest
      ILLUMINATE_VERSION: 5.6
      TESTBENCH_VERSION: 3.6

    <<: *default_steps

workflows:
  version: 2
  build:
    jobs:
      - php-7.0-l-5.4
      - php-7.0-lowest-l-5.4
      - php-7.0-l-5.5
      - php-7.0-lowest-l-5.5
      - php-7.1-l-5.6
      - php-7.1-lowest-l-5.6
      - php-7.2-l-5.4
      - php-7.2-lowest-l-5.4
      - php-7.2-l-5.5
      - php-7.2-lowest-l-5.5
      - php-7.2-l-5.6
      - php-7.2-lowest-l-5.6
